import = ["~/.config/alacritty/themes/alacritty-theme/themes/cyber_punk_neon.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
opacity = 0.7
blur = true

[scrolling]
history = 100000

[font]
#normal = { family = "Ubuntu Mono derivative Powerline" }
#bold = { family = "Ubuntu Mono derivative Powerline" }
#italic = { family = "Ubuntu Mono derivative Powerline" }
#bold_italic = { family = "Ubuntu Mono derivative Powerline" }
normal = { family = "MesloLGS Nerd Font Mono" }
bold = { family = "MesloLGS Nerd Font Mono" }
italic = { family = "MesloLGS Nerd Font Mono" }
bold_italic = { family = "MesloLGS Nerd Font Mono" }
fallback = { family = "Ubuntu Mono derivative Powerline" }
size = 13.5
# [colors]
# primary = []

[cursor]
style = { shape = "Beam" }
