import = ["~/.config/alacritty/themes/alacritty-theme/themes/cyber_punk_neon.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
opacity = 0.7
blur = true

[scrolling]
history = 100000

[font]
normal = { family = "FiraCode Nerd Font Propo" }
bold = { family = "FiraCode Nerd Font Propo" }
italic = { family = "FiraCode Nerd Font Propo" }
bold_italic = { family = "FiraCode Nerd Font Propo" }
size = 13.5
# [colors]
# primary = []

[cursor]
style = { shape = "Beam" }
